base_url = "https://kirusfg.com"

title = "kirusfg"
description = "kirusfg's personal website"

theme = "apollo"

default_language = "en"

compile_sass = true
build_search_index = true

[markdown]
highlight_code = true
highlight_theme = "gruvbox-light"

[extra]
menu = [
    { name = "/about", url = "/about", weight = 3 },
    { name = "/projects", url = "/projects", weight = 2 },
    { name = "/posts", url = "/posts", weight = 1 },
]

stylesheets = [
    "main_override.css",
    "theme/gruvbox_light.css",
    "theme/fonts.css",
]
